name: junitconfiguration
version: 1.1.0
author: Lukas Renggli <renggli@gmail.com>
description: A test configuration producing JUnit compatible output.
homepage: https://github.com/renggli/dart-junit
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  unittest: '>=0.11.0 <0.12.0'
